### ISSUE TITLE
Logical race condition

### ISSUE THREAD

**Issue by Lazarscorro** [Suffuse-Team/suffuse-team.github.io#1]
Logical race conditions are errors that produce logically incorrect results, but no overt programming error. Logical race conditions are triggered when multiple operations are happening concurrently. Logical race conditions are common in sql based web systems. Multiple web requests can occur simultaneously, each triggering a corresponding database request. The concurrent web requests can trigger database to access the same resources at the same time.

**Comment by EshayDev** [comment]
closing due to shitpost 💀 (go find somewhere else to do this)
